# To run a container using this image you must provide a database url in env vars
# Note: db.sqlite3 won’t work

FROM python:3.9-alpine3.13

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-deps \
        build-base postgresql-dev musl-dev linux-headers && \
    /py/bin/pip install -r requirements.txt && \
    apk del .tmp-deps && \
    adduser --disabled-password --no-create-home app-user

COPY . .

ENV PATH="/py/bin:$PATH"

USER app-user

EXPOSE 8080

CMD ["sh", "./run-dev.sh"]
